### ISSUE TITLE
Document how to populate the MRI protocol tables

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#372]
Document how to fill in the `mri_protocol` table including how to set the regex series description field (no` / /i`).
 + Nicolas' project, subproject structure

- Also better documentation on how to support unknown acquisitions. 

- Also, document how to rename the environment file to a different file and source it instead of using the one on the branch that gets overwritten when changing branches

**Comment by cmadjar** [comment]
This ticket is dependant on the two following PRs:
- https://github.com/aces/Loris-MRI/pull/339
- https://github.com/aces/Loris-MRI/pull/369

**Comment by cmadjar** [comment]
@nicolasbrossard do you think this is still applicable? If so, @christinerogers , this could be another task for a Google season of docs.

**Comment by nicolasbrossard** [comment]
@cmadjar @christinerogers Yes, this is still applicable.

**Comment by christinerogers** [comment]
@cmadjar could i split this task with you for the 25 release? 
there are 3 bullets in the description at top: 
- [ ] document how to rename the environment file to a different file and source it instead of using the one on the branch that gets overwritten when changing branches
-> could you do this one? 

I could take care of the last 2 working with an expert like @nicolasbrossard - to do these ones: 
- [ ] Nicolas' project, subproject structure (and `series description` field?)
- [ ] Also better documentation on how to support unknown acquisitions.
