### ISSUE TITLE
Implement CandidateOB.pm

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#457]
Implement the new CandidateOB.pm, which will be used to perform queries on table `candidate`

**Comment by cmadjar** [comment]
Comment from @xlecours on the agenda of the LORIS imaging call: 

Implement CandidateOB.pm
Instead of : “Implement the new CandidateOB.pm, which will be used to perform queries on table candidate”, I will use LORIS API’s to query candidate’s data. I’ll need to add https://perldoc.perl.org/HTTP::Tiny as a dependency.
